name: CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: go vet .
          golint .
